[external]
build-requires = [
  "dep:virtual/compiler/c",
  "dep:virtual/compiler/cxx",
  "dep:virtual/compiler/fortran",
  "dep:generic/ninja",
  "dep:generic/pkg-config",
]
build-host-requires = [
  "dep:virtual/interface/blas",
  "dep:virtual/interface/lapack",
]
