[external]
build-requires = [
  "dep:virtual/compiler/c",
]
build-host-requires = [
  "dep:generic/libjpeg",
  "dep:generic/zlib",
]

[external.optional-build-host-requires]
extra = [
  "dep:generic/lcms2",
  "dep:generic/freetype",
  "dep:generic/libimagequant",
  "dep:generic/libraqm",
  "dep:generic/libtiff",
  "dep:generic/libxcb",
  "dep:generic/libwebp",
  "dep:generic/openjpeg@>=2.0",
  "dep:generic/tk",
]
